# permissions for end users to view critconfigtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: critconfigtemplate-viewer-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - critconfigtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - critconfigtemplates/status
  verbs:
  - get
