# permissions for end users to edit critconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: critconfig-editor-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - critconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - critconfigs/status
  verbs:
  - get
