namePrefix: cabpc-

commonLabels:
  cluster.x-k8s.io/provider: "bootstrap-crit"

bases:
- crd
- default
- webhook

patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: critconfigs.bootstrap.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: critconfigtemplates.bootstrap.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: critcontrolplanes.controlplane.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
